CREATE DATABASE college_library;
USE college_library;

DROP TABLE LIBRARIAN;
DROP TABLE RESOURCES;
DROP TABLE AUTHOR;
DROP TABLE PUBLISHER; 
DROP TABLE SUBJECT;
DROP TABLE BORROWER;
DROP TABLE RESOURCES;
DROP TABLE LOAN;
DROP TABLE LOAN_DUE;
DROP TABLE LOAN_SEQUENCE;

CREATE TABLE LIBRARIAN 
	(LIBRARIAN_ID INT NOT NULL, 
	HOURS FLOAT, 
	DATE_OF_JOINING DATE,
	CONSTRAINT LIBRARIAN_PK PRIMARY KEY (LIBRARIAN_ID) 
); 

CREATE TABLE RESOURCES 
	(BARCODE INT NOT NULL, 
	TITLE VARCHAR (255) NOT NULL, 
	COPIES INT NOT NULL, 
	LOAN_LENGTH INT NOT NULL,
	CONSTRAINT RESOURCE_PK PRIMARY KEY (BARCODE)
); 

CREATE TABLE AUTHOR 
	(BARCODE INT NOT NULL, 
	AUTHOR_NAME VARCHAR (255), 
	CONSTRAINT AUTHOR_FK 
	  FOREIGN KEY (BARCODE) 
	  REFERENCES RESOURCES(BARCODE) 
); 

CREATE TABLE PUBLISHER 
	(BARCODE INT NOT NULL, 
	RESOURCE_TYPE VARCHAR (255) NOT NULL, 
	PUBLISHER VARCHAR (255), 
	PUBLICATION_DATE INT, 
	EDITION INT, 
	CONSTRAINT PUBLISHER_FK
	  FOREIGN KEY (BARCODE) 
	  REFERENCES RESOURCES(BARCODE) 
); 

CREATE TABLE SUBJECT 
	(BARCODE INT NOT NULL,
	CLASS_NO INT NOT NULL, 
	SUBJECT_NAME VARCHAR(255), 
	FLOOR_NO INT NOT NULL, 
	SHELF_NO INT NOT NULL,
	CONSTRAINT SUB_FK
	  FOREIGN KEY (BARCODE)
	  REFERENCES RESOURCES(BARCODE)
);

CREATE TABLE BORROWER  
	(BORROWER_ID int, 
	F_NAME VARCHAR (150), 
	L_NAME VARCHAR (200), 
	EMAIL VARCHAR (200), 
	PAID_STATUS CHAR(1), -- THE INPUT WIIL BE EITHER Y OR N --
	ACTIVE_STATUS CHAR(1),
	TYPE VARCHAR (7),
	CONSTRAINT BORROWER_PK PRIMARY KEY (BORROWER_ID)
); 



CREATE TABLE LOAN 
	(LOAN_ID INT NOT NULL, 
	ISSUE_DATE DATE NOT NULL,  
	RETURN_DATE DATE, 
	BARCODE INT NOT NULL, 
	BORROWER_ID INT NOT NULL, 
	CONSTRAINT L_PK PRIMARY KEY (LOAN_ID),
	CONSTRAINT BARC_FK  
	  FOREIGN KEY (BARCODE) 
	  REFERENCES RESOURCES(BARCODE), 
	CONSTRAINT BORR_FK
	  FOREIGN KEY (BORROWER_ID) 
	  REFERENCES BORROWER(BORROWER_ID)
	  -- ON DELETE CASCADE -- 
	-- CONSTRAINT CHECK_ISSUE_DATE CHECK (ISSUE_DATE < DATE_OF_RETURN) 
);
  
CREATE TABLE loan_sequence (
   id INT NOT NULL AUTO_INCREMENT,
   value INT NOT NULL,
   PRIMARY KEY (id)
);


CREATE TABLE LOAN_DUE 
	(LOAN_ID INT, 
	BARCODE INT,
	DUE_DATE DATE,
	CONSTRAINT L_FK
	  FOREIGN KEY (LOAN_ID) 
	  REFERENCES LOAN(LOAN_ID), 
	CONSTRAINT BC_FK
	  FOREIGN KEY (BARCODE) 
	  REFERENCES RESOURCES(BARCODE) 
);  

INSERT INTO LIBRARIAN (LIBRARIAN_ID, HOURS, DATE_OF_JOINING) VALUES (3029383, 12, DATE_FORMAT("13-AUG-2018", "%d-%b-%Y"));
INSERT INTO LIBRARIAN (LIBRARIAN_ID, HOURS, DATE_OF_JOINING) VALUES (2342554, 37.5, DATE_FORMAT("24-JAN-2015", "%d-%b-%Y"));
INSERT INTO LIBRARIAN (LIBRARIAN_ID, HOURS, DATE_OF_JOINING) VALUES (4524675, 16, DATE_FORMAT("05-SEP-2019", "%d-%b-%Y"));
INSERT INTO LIBRARIAN (LIBRARIAN_ID, HOURS, DATE_OF_JOINING) VALUES (2456546, 30, DATE_FORMAT("21-NOV-2019", "%d-%b-%Y"));
INSERT INTO LIBRARIAN (LIBRARIAN_ID, HOURS, DATE_OF_JOINING) VALUES (1232534, 37.5, DATE_FORMAT("19-JUN-2017", "%d-%b-%Y"));
INSERT INTO LIBRARIAN (LIBRARIAN_ID, HOURS, DATE_OF_JOINING) VALUES (5675456, 8, DATE_FORMAT("11-OCT-2020", "%d-%b-%Y"));
INSERT INTO LIBRARIAN (LIBRARIAN_ID, HOURS, DATE_OF_JOINING) VALUES (1345136, 40, DATE_FORMAT("30-APR-2014", "%d-%b-%Y"));


